### ISSUE TITLE
조사모아 라이브러리 로고

### ISSUE THREAD

**Issue by kycasdzxc** [josa-moa/josa-moa#1]
조사모아 라이브러리 로고

**Comment by clou-dd** [comment]
##조사모아 라이브러리 로고 러프 스케치안
<img src=https://user-images.githubusercontent.com/113405581/191260453-19912840-bee8-4e9c-a948-6a7723d2bd43.jpg width=45%> <img src=https://user-images.githubusercontent.com/113405581/191261422-63219ccd-fa14-4ee5-825a-3dc0e286a625.jpg width=45%>
- 조사모아의 자음을 따서 그래픽화 하였습니다.
- 색깔은 단색과 메탈 느낌의 두 종류로 입혀서 만들어보았습니다.

**Comment by kycasdzxc** [comment]
@cloudd81 로고 진짜 미쳤다리...... 너무 좋아요 만족쓰🤩

**Comment by clou-dd** [comment]
@kycasdzxc ㅋㅋㅋㅋ다행이옵니돠
