### ISSUE TITLE
격에 따른 조사 정리

### ISSUE THREAD

**Issue by kycasdzxc** [josa-moa/josa-moa#16]
#15 에 추가된 Constant 클래스에 enum 형식으로 조사 정리해주시면 됩니다.
변수명은 #2 에 정리해놓겠습니다!

**Comment by clou-dd** [comment]
넷!!! 알겠습니다!

**Comment by kycasdzxc** [comment]
@cloudd81 enum 사용은 번거로운 거 같아서 String 배열로 선언하겠습니당
