### ISSUE TITLE
영문자, 특수문자에 따른 해결방법

### ISSUE THREAD

**Issue by kycasdzxc** [josa-moa/josa-moa#27]
현재 짜놓은 코드는 온전히 한글 유니코드만 걸러내고 있습니다.
영어나 특수문자일 경우에는 어떻게 처리할지 정해야 합니다.

**Comment by clou-dd** [comment]
무식하니까 올릴 수 있는 아이디어!(ㅋㅋㅋ)

[http://www.koreascience.kr/article/CFKO199829013511572.pdf](url)
영어와 같은 경우에는 '한글 및 한국어 정보처리 학술대회' 아티클의 정보를 살펴보니 영어 발음을 유종성, 무종성, ㄹ종성으로 나누어서 조사의 형태를 구분하여 붙이는 것으로 정리가 되어있던데..
알고리즘도 나와있어서 제 수준에서는 어려워보이지만 잘 연구해서 코드를 짜면 충분히 구현 가능하지 않을까 하는 생각이 들었습니다.

그리고 이건 또 하나의 스쳐가는 생각!
[http://loanword.cs.pusan.ac.kr/](url)

위 링크의 부산대에서 제공하는 외래어 <-> 한글 상호 변환 시스템을 활용하여 한글 표기로 변환한 뒤 그 표기를 가져와서 한글 조사 붙이는 알고리즘에 그대로 대입시키는 건 어려울까유?
잘 모르겠네요

**Comment by kycasdzxc** [comment]
@cloudd81 두 링크 모두 확인했습니다!

'한글 및 한국어 정보처리 학술대회' 아티클은 유용하긴 하나 저 또한 적용하기에는 어려운 부분.... 완전 인공지능쓰

두 번째도 생각하긴 했는데, 이게 크롤링 같은 '스크래핑' 개념인데 매번 그럼 쓸 때마다 저 사이트 찍고 오고 하는 게 너무 비효율적이란 생각이 들었습니다 허허.... 최대한 코드로 구현하는 게 좋을 듯
