### ISSUE TITLE
조사 변환 메서드 프로세스 분석

### ISSUE THREAD

**Issue by kycasdzxc** [josa-moa/josa-moa#28]
@cloudd81 조사 변환 메서드 관련 프로세스를 분석해보시면 좋겠습니다.
#29 에 추가한 주석이 있는 위치를 보시면 됩니다. (StringUtil 클래스의 main 메서드 참고)

조사 분석이 어떻게 되는건지에 대한 개념을 정리해서 여기에 코멘트로 남겨주세요.

**Comment by clou-dd** [comment]
오류가 있다면 잡아주시길 부탁드려요- :)
@kycasdzxc @im-dullin 

<br><hr><br>
**1. proc 메서드 : 문자열 str의 맨 마지막 글자의 종성의 여부를 알아보는 메서드**

public static String proc(String str, String s1, String s2) { 
	return (str.charAt(str.length()-1) - '가') % 28 != 0 ? str + s1 : str + s2;
}

에서 str.charAt(str.length()-1) 는 문자열의 가장 마지막 문자를 유니코드 값으로 출력.
이 문자에서 - '가' 를 빼고(한글의 시작점)  % 28(종성의 개수로 나눈 후 나머지 값 구하기) 를 하면 종성 위치값을 파악할 수 있다(종성의 0번째는 받침이 없는 경우).

종성의 여부를 파악한 후 s1과 s2는 checkPosition으로 파악된 격에 맞춘 조사가 부여됌.


**2. checkdPosition() 메서드 : 문자열에 붙을 조사가 어떤 조사가 오면 되는지 분석하는 메서드.**

josamoa.setS("예찬", "이가")

'예찬' 이라는 문자 뒤에 '이가' 라는 조사를 붙였을 때 '이가'가 어떤 격의 조사인 지를 분류하고 proc 메서드와 함께 종성 여부를 파악하여 '이' 또는 '가'의 조사를 배치해준다... 라고 봤는데 이 메서드는 정확하게 이해한 느낌은 아니네요.

<br><hr><br>
우선 지금까지 이해한 것을 바탕으로 올려봅니다.
살펴보면서 다르게 이해하거나 하면 또 코멘트로 올릴게요~

**Comment by kycasdzxc** [comment]
@cloudd81 설명 너무 잘 해주셨네요! 자료를 남겨놓고자 조금만 첨언하자면..

<h3>1. proc 메서드</h3>

한글 글자의 총 갯수(가~힣)는 총 11172개이며, 각 자음 별로 588개의 글자를 갖고 있습니다.
그리고 이 글자들은 모음을 기준으로 정확히 28개씩 나눠집니다.

ㄱ을 예시로 보자면, 
가각갂갃간갅갆갇갈갉갊갋갌갍갎갏감갑값갓갔강갖갗갘같갚갛
개객갞갟갠갡갢갣갤갥갦갧갨갩갪갫갬갭갮갯갰갱갲갳갴갵갶갷
                                              ...
긔긕긖긗긘긙긚긛긜긝긞긟긠긡긢긣긤긥긦긧긨긩긪긫긬긭긮긯
기긱긲긳긴긵긶긷길긹긺긻긼긽긾긿김깁깂깃깄깅깆깇깈깉깊깋

이처럼 각 모음의 첫 번째 글자만 받침이 없는 글자이기에 '글자' % 28 != 0 이라는 식이 성립된 것입니다.

<hr>

<h3>2. checkdPosition() 메서드</h3>

사실 제대로 분석하신 게 맞습니다. 조사의 격을 체크하고, 해당 격 내에 어떤 조사인지를 체크하는 용도로 만들기는 했는데..
조사의 종류가 매우 한정적이라 굳이 상수로 선언할 필요가 있는가라는 의문과 더불어 매우 비효율적인 코드이지 않나라는 생각이 듭니다. 이는 우리가 함께 보완해 나가야 할 부분이라 생각합니다.

정말 좋은 comment였습니다, 굿굿! 👍🏻
