### ISSUE TITLE
주어 조사 처리(은는이가)

### ISSUE THREAD

**Issue by kycasdzxc** [josa-moa/josa-moa#3]
- 주어의 조사 처리
  과일 -> 과일 '은',  사과 -> 사과 '는'
  철수 -> 철수 '가',  예찬 -> 예찬 '이가'

* 메서드 파리미터로 문자열을 받아 처리하면 좋겠다는 생각.
ex) 메서드명(문자열, "은는"), 메서드명(문자열, "이가")

**Comment by im-dullin** [comment]
eunNeun, iGa

**Comment by kycasdzxc** [comment]
> 은은, iGa

@im-dullin 설계 생각했을 때, 조사의 수는 변함이 없으니까..
Constant 클래스를 하나 만들고 거기 안에 String 배열을 만들어서 관리하면 어떨까 생각해봤음.
ex) final String[] SUBJECTIVE = {"은는", "이가"};

**Comment by kycasdzxc** [comment]
> > 은은, iGa
> 
> @im-dullin 설계 생각했을 때, 조사의 수는 변함이 없으니까.. Constant 클래스를 하나 만들고 거기 안에 String 배열을 만들어서 관리하면 어떨까 생각해봤음. ex) final String[] SUBJECTIVE = {"은는", "이가"};

이거는 내가 #2 에다가 다시 정리해서 올리겠음

**Comment by im-dullin** [comment]
> > 은은, iGa
> 
> @im-dullin 설계 생각했을 때, 조사의 수는 변함이 없으니까.. Constant 클래스를 하나 만들고 거기 안에 String 배열을 만들어서 관리하면 어떨까 생각해봤음. ex) final String[] SUBJECTIVE = {"은는", "이가"};

변함없는 값, 정해진 수 > Constant클래스에 enum배열 또는 순수 문자열 배열 쏘 굿!

**Comment by kycasdzxc** [comment]
> > > 은은, iGa
> > 
> > 
> > @im-dullin 설계 생각했을 때, 조사의 수는 변함이 없으니까.. Constant 클래스를 하나 만들고 거기 안에 String 배열을 만들어서 관리하면 어떨까 생각해봤음. ex) final String[] SUBJECTIVE = {"은는", "이가"};
> 
> 변함없는 값, 정해진 수 > Constant클래스에 enum배열 또는 순수 문자열 배열 쏘 굿!

@im-dullin enum을 활용하는 게 좋을 듯. 그럼 Constant 클래스 따로 안만들어도 될 거 같기도 하구..?

https://velog.io/@nawhew/%EC%9E%90%EB%B0%94-Enum%EC%9D%84-%EB%8D%94-%EC%9E%98%EC%93%B0%EA%B8%B0-%EC%9C%84%ED%95%9C-%EB%B0%A9%EB%B2%95

**Comment by im-dullin** [comment]
> > > > 은은, iGa
> > > 
> > > 
> > > @im-dullin 설계 생각했을 때, 조사의 수는 변함이 없으니까.. Constant 클래스를 하나 만들고 거기 안에 String 배열을 만들어서 관리하면 어떨까 생각해봤음. ex) final String[] SUBJECTIVE = {"은는", "이가"};
> > 
> > 
> > 변함없는 값, 정해진 수 > Constant클래스에 enum배열 또는 순수 문자열 배열 쏘 굿!
> 
> @im-dullin enum을 활용하는 게 좋을 듯. 그럼 Constant 클래스 따로 안만들어도 될 거 같기도 하구..?
> 
> https://velog.io/@nawhew/%EC%9E%90%EB%B0%94-Enum%EC%9D%84-%EB%8D%94-%EC%9E%98%EC%93%B0%EA%B8%B0-%EC%9C%84%ED%95%9C-%EB%B0%A9%EB%B2%95


I don't think there's a better idea than that.
