### ISSUE TITLE
라이브러리 생성 패턴에 대한 고찰

### ISSUE THREAD

**Issue by kycasdzxc** [josa-moa/josa-moa#32]
S, V O, C 등 문장의 형식을 변수로 지정하여서!

josamoa.setS("철수").setO("밥").setV("먹는다") 이런 식으로 메서드 체이닝하고 toString()으로 세팅해서 System.out.println(josamoa); 로 하면 '철수가 밥을 먹는다.' 라는 식의 문장이 나오게 하는 방식!

@im-dullin @cloudd81 어떻게 생각하시나요들?

**Comment by kycasdzxc** [comment]
찾아보니까 이 방식이 생성 패턴 중 빌드 패턴인 듯 합니다.

#33 의 내용을 확인해주세요.

**Comment by im-dullin** [comment]
> 찾아보니까 이 방식이 생성 패턴 중 빌드 패턴인 듯 합니다.
> 
> #33 의 내용을 확인해주세요.

글 정리 감사합니다.

그럼 저희의 필수 메서드는 주어가 되는건가요?

**Comment by kycasdzxc** [comment]
> > 찾아보니까 이 방식이 생성 패턴 중 빌드 패턴인 듯 합니다.
> > #33 의 내용을 확인해주세요.
> 
> 글 정리 감사합니다.
> 
> 그럼 저희의 필수 메서드는 주어가 되는건가요?

새로운 객체 생성 시(객체 빌드 시)를 말하시는거죠?

생성자 파라미터로 주어와 동사를 필수로 넣을까 고민 중입니다.
보어가 들어오면 동사 안쓰고 S+C로 해야하나 이런저런 고민 중..

**Comment by clou-dd** [comment]
> 찾아보니까 이 방식이 생성 패턴 중 빌드 패턴인 듯 합니다.
> 
> #33 의 내용을 확인해주세요.

공유 고맙습니답
저 분이 올려주신 연관 게시글도 다 읽어봐야지 다 이해할 수 있으려나 싶네요.

그러게요!
필수 메서드로 주어는 꼭 넣어야 할거고, 동사는 문장 구성에서 빠지는 경우가 있지만 빈도 수가 높아서..
고민되는 영역..
