### ISSUE TITLE
목적어 조사 처리(을를)

### ISSUE THREAD

**Issue by kycasdzxc** [josa-moa/josa-moa#4]
목적어의 조사 처리
과일 -> 과일 '을', 사과 -> 사과 '를'
철수 -> 철수 '를', 예찬 -> 예찬 '이를'

메서드 파리미터로 문자열을 받아 처리하면 좋겠다는 생각.
ex) 메서드명(문자열, "을를"), 메서드명(문자열, "이를")

**Comment by im-dullin** [comment]
eulLeul, eLoul

**Comment by kycasdzxc** [comment]
@im-dullin 서술격, 목적격, 보격, 부사격, 관형격 모두 메서드 생성해주시면 됩니다.

**Comment by kycasdzxc** [comment]
해당 작업은 @im-dullin -> @cloudd81 로 변경합니다.

**Comment by clou-dd** [comment]
#31
로 pull-req 해두었습니다~~
